name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        continue-on-error: true

      - name: Run Build
        run: |
          sudo mkdir -p ./library-api
          npm run build >> ./library-api/deploy.log 2>&1 || {
            echo "Build failed at $(date)" >>./library-api/deploy.log
            exit 1
          }

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop services
            sudo systemctl stop caddy || log_message "Warning: Caddy stop failed"
            sudo systemctl stop mysql || log_message "Warning: MySQL stop failed"

            # Install dependencies
            npm install

            # Run database migrations
            npm run migrate:prod

            # Build the project
            npm run build

            # Restart services
            sudo systemctl start mysql

            # Start/Restart PM2 process
            sudo systemctl start caddy

      - name: Upload deployment logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deployment-logs
          path: /home/ubuntu/library-api/deploy.log
